name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Cloudflared
      run: |
        sudo apt-get update
        sudo apt-get install -y wget
        wget https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
        sudo dpkg -i cloudflared-linux-amd64.deb

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        echo -e "Host lock1\n\tHostName ssh.golockedin.com\n\tProxyCommand cloudflared access ssh --hostname %h\n\tUser maanav\n\tIdentityFile ~/.ssh/id_rsa\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

    - name: Build Docker image
      run: docker build -t myapp .

    - name: Save Docker image to tar
      run: docker save myapp > myapp.tar

    - name: Copy Docker image to server
      run: |
        scp -F ~/.ssh/config myapp.tar lock1:/home/maanav/

    - name: Load Docker image on server and run
      run: |
        ssh -F ~/.ssh/config lock1 << 'EOF'
        docker load < /home/maanav/myapp.tar
        docker stop myapp_container || true
        docker rm myapp_container || true
        docker run -d --name myapp_container -p 80:3000 myapp
        EOF
