name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        echo "Host ssh.golockedin.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

    - name: Build Docker image
      run: docker build -t myapp .

    - name: Save Docker image to tar
      run: docker save myapp > myapp.tar

    - name: Copy Docker image to server
      run: |
        scp -o ProxyCommand="cloudflared access ssh --hostname %h" myapp.tar ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/maanav/

    - name: Load Docker image on server and run
      run: |
        ssh -o ProxyCommand="cloudflared access ssh --hostname %h" ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
        docker load < /home/maanav/myapp.tar
        docker stop myapp_container || true
        docker rm myapp_container || true
        docker run -d --name myapp_container -p 80:3000 myapp
        EOF
